# Generated by Django 4.1 on 2022-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='list',
            name='heading',
            field=models.CharField(default='', max_length=200),
        ),
    ]
